export const COUNTRIES = [
    { id: 1, country: { label: 'Russia', code: 'RU' }, checked: false },
    { id: 2, country: { label: 'Canada', code: 'CA' }, checked: false },
    { id: 3, country: { label: 'Brazil', code: 'BR' }, checked: false },
    { id: 4, country: { label: 'Australia', code: 'AU' }, checked: false },
    { id: 5, country: { label: 'China', code: 'CN' }, checked: false },
    { id: 6, country: { label: 'India', code: 'IN' }, checked: false },
    { id: 7, country: { label: 'United States', code: 'US' }, checked: false },
    { id: 8, country: { label: 'Mexico', code: 'MX' }, checked: false },
    { id: 9, country: { label: 'South Africa', code: 'ZA' }, checked: false },
    {
        id: 10,
        country: { label: 'United Kingdom', code: 'GB' },
        checked: false,
    },
    { id: 11, country: { label: 'Germany', code: 'DE' }, checked: false },
    { id: 12, country: { label: 'France', code: 'FR' }, checked: false },
    { id: 13, country: { label: 'Italy', code: 'IT' }, checked: false },
    { id: 14, country: { label: 'Spain', code: 'ES' }, checked: false },
    { id: 15, country: { label: 'Japan', code: 'JP' }, checked: false },
    { id: 16, country: { label: 'South Korea', code: 'KR' }, checked: false },
    { id: 17, country: { label: 'Argentina', code: 'AR' }, checked: false },
    { id: 18, country: { label: 'Egypt', code: 'EG' }, checked: false },
    { id: 19, country: { label: 'Turkey', code: 'TR' }, checked: false },
    { id: 20, country: { label: 'Saudi Arabia', code: 'SA' }, checked: false },
    { id: 21, country: { label: 'Nigeria', code: 'NG' }, checked: false },
    { id: 22, country: { label: 'Indonesia', code: 'ID' }, checked: false },
    { id: 23, country: { label: 'Pakistan', code: 'PK' }, checked: false },
    { id: 24, country: { label: 'Bangladesh', code: 'BD' }, checked: false },
    { id: 25, country: { label: 'Iran', code: 'IR' }, checked: false },
    { id: 26, country: { label: 'Vietnam', code: 'VN' }, checked: false },
    { id: 27, country: { label: 'Philippines', code: 'PH' }, checked: false },
    { id: 28, country: { label: 'Thailand', code: 'TH' }, checked: false },
    { id: 29, country: { label: 'Myanmar', code: 'MM' }, checked: false },
    { id: 30, country: { label: 'Kenya', code: 'KE' }, checked: false },
    { id: 31, country: { label: 'Ukraine', code: 'UA' }, checked: false },
    { id: 32, country: { label: 'Poland', code: 'PL' }, checked: false },
    { id: 33, country: { label: 'Tanzania', code: 'TZ' }, checked: false },
    { id: 34, country: { label: 'Sudan', code: 'SD' }, checked: false },
    { id: 35, country: { label: 'Uganda', code: 'UG' }, checked: false },
    { id: 36, country: { label: 'Morocco', code: 'MA' }, checked: false },
    { id: 37, country: { label: 'Peru', code: 'PE' }, checked: false },
    { id: 38, country: { label: 'Malaysia', code: 'MY' }, checked: false },
    { id: 39, country: { label: 'Venezuela', code: 'VE' }, checked: false },
    { id: 40, country: { label: 'Ghana', code: 'GH' }, checked: false },
    { id: 41, country: { label: 'Nepal', code: 'NP' }, checked: false },
    { id: 42, country: { label: 'Madagascar', code: 'MG' }, checked: false },
    { id: 43, country: { label: 'Cameroon', code: 'CM' }, checked: false },
    { id: 44, country: { label: 'Ivory Coast', code: 'CI' }, checked: false },
    { id: 45, country: { label: 'North Korea', code: 'KP' }, checked: false },
    { id: 46, country: { label: 'Australia', code: 'AU' }, checked: false },
    { id: 47, country: { label: 'Niger', code: 'NE' }, checked: false },
    { id: 48, country: { label: 'Taiwan', code: 'TW' }, checked: false },
    { id: 49, country: { label: 'Yemen', code: 'YE' }, checked: false },
    { id: 50, country: { label: 'Iraq', code: 'IQ' }, checked: false },
    { id: 51, country: { label: 'Mozambique', code: 'MZ' }, checked: false },
    { id: 52, country: { label: 'Romania', code: 'RO' }, checked: false },
    { id: 53, country: { label: 'Chile', code: 'CL' }, checked: false },
    { id: 54, country: { label: 'Syria', code: 'SY' }, checked: false },
    { id: 55, country: { label: 'Kazakhstan', code: 'KZ' }, checked: false },
    { id: 56, country: { label: 'Zambia', code: 'ZM' }, checked: false },
    { id: 57, country: { label: 'Guatemala', code: 'GT' }, checked: false },
    { id: 58, country: { label: 'Ecuador', code: 'EC' }, checked: false },
    { id: 59, country: { label: 'Netherlands', code: 'NL' }, checked: false },
    { id: 60, country: { label: 'Senegal', code: 'SN' }, checked: false },
    { id: 61, country: { label: 'Cambodia', code: 'KH' }, checked: false },
    { id: 62, country: { label: 'Chad', code: 'TD' }, checked: false },
    { id: 63, country: { label: 'Somalia', code: 'SO' }, checked: false },
    { id: 64, country: { label: 'Zimbabwe', code: 'ZW' }, checked: false },
    { id: 65, country: { label: 'Guinea', code: 'GN' }, checked: false },
    { id: 66, country: { label: 'Rwanda', code: 'RW' }, checked: false },
    { id: 67, country: { label: 'Benin', code: 'BJ' }, checked: false },
    { id: 68, country: { label: 'Tunisia', code: 'TN' }, checked: false },
    { id: 69, country: { label: 'Bolivia', code: 'BO' }, checked: false },
    { id: 70, country: { label: 'Belgium', code: 'BE' }, checked: false },
    { id: 71, country: { label: 'Cuba', code: 'CU' }, checked: false },
    { id: 72, country: { label: 'Haiti', code: 'HT' }, checked: false },
    { id: 73, country: { label: 'Greece', code: 'GR' }, checked: false },
    { id: 74, country: { label: 'Jordan', code: 'JO' }, checked: false },
    {
        id: 75,
        country: { label: 'Czech Republic', code: 'CZ' },
        checked: false,
    },
    { id: 76, country: { label: 'Portugal', code: 'PT' }, checked: false },
    { id: 77, country: { label: 'Sweden', code: 'SE' }, checked: false },
    { id: 78, country: { label: 'Azerbaijan', code: 'AZ' }, checked: false },
    { id: 79, country: { label: 'Hungary', code: 'HU' }, checked: false },
    {
        id: 80,
        country: { label: 'United Arab Emirates', code: 'AE' },
        checked: false,
    },
    { id: 81, country: { label: 'Honduras', code: 'HN' }, checked: false },
    { id: 82, country: { label: 'Belarus', code: 'BY' }, checked: false },
    { id: 83, country: { label: 'Tajikistan', code: 'TJ' }, checked: false },
    { id: 84, country: { label: 'Israel', code: 'IL' }, checked: false },
    { id: 85, country: { label: 'Switzerland', code: 'CH' }, checked: false },
    { id: 86, country: { label: 'Sierra Leone', code: 'SL' }, checked: false },
    { id: 87, country: { label: 'Hong Kong', code: 'HK' }, checked: false },
    { id: 88, country: { label: 'Laos', code: 'LA' }, checked: false },
    { id: 89, country: { label: 'Paraguay', code: 'PY' }, checked: false },
    { id: 90, country: { label: 'Libya', code: 'LY' }, checked: false },
    { id: 91, country: { label: 'Nicaragua', code: 'NI' }, checked: false },
    { id: 92, country: { label: 'El Salvador', code: 'SV' }, checked: false },
    { id: 93, country: { label: 'Kyrgyzstan', code: 'KG' }, checked: false },
    { id: 94, country: { label: 'Lebanon', code: 'LB' }, checked: false },
    { id: 95, country: { label: 'Singapore', code: 'SG' }, checked: false },
    { id: 96, country: { label: 'Denmark', code: 'DK' }, checked: false },
    { id: 97, country: { label: 'Finland', code: 'FI' }, checked: false },
    { id: 98, country: { label: 'Slovakia', code: 'SK' }, checked: false },
    { id: 99, country: { label: 'Norway', code: 'NO' }, checked: false },
    { id: 100, country: { label: 'Ireland', code: 'IE' }, checked: false },
]
export const LANGUAGES = [
    { id: 1, language: { label: 'Russian', code: 'RU' }, checked: false },
    { id: 2, language: { label: 'English', code: 'EN' }, checked: false },
    { id: 3, language: { label: 'Spanish', code: 'ES' }, checked: false },
    { id: 4, language: { label: 'French', code: 'FR' }, checked: false },
    { id: 5, language: { label: 'German', code: 'DE' }, checked: false },
    { id: 6, language: { label: 'Italian', code: 'IT' }, checked: false },
    { id: 7, language: { label: 'Portuguese', code: 'PT' }, checked: false },
    { id: 8, language: { label: 'Dutch', code: 'NL' }, checked: false },
    { id: 9, language: { label: 'Swedish', code: 'SV' }, checked: false },
    { id: 10, language: { label: 'Norwegian', code: 'NO' }, checked: false },
    { id: 11, language: { label: 'Danish', code: 'DA' }, checked: false },
    { id: 12, language: { label: 'Finnish', code: 'FI' }, checked: false },
    { id: 13, language: { label: 'Japanese', code: 'JA' }, checked: false },
    { id: 14, language: { label: 'Chinese', code: 'ZH' }, checked: false },
    { id: 15, language: { label: 'Korean', code: 'KO' }, checked: false },
    { id: 16, language: { label: 'Arabic', code: 'AR' }, checked: false },
    { id: 17, language: { label: 'Hebrew', code: 'HE' }, checked: false },
    { id: 18, language: { label: 'Turkish', code: 'TR' }, checked: false },
    { id: 19, language: { label: 'Greek', code: 'EL' }, checked: false },
    { id: 20, language: { label: 'Polish', code: 'PL' }, checked: false },
    { id: 21, language: { label: 'Czech', code: 'CS' }, checked: false },
    { id: 22, language: { label: 'Slovak', code: 'SK' }, checked: false },
    { id: 23, language: { label: 'Hungarian', code: 'HU' }, checked: false },
    { id: 24, language: { label: 'Romanian', code: 'RO' }, checked: false },
    { id: 25, language: { label: 'Bulgarian', code: 'BG' }, checked: false },
    { id: 26, language: { label: 'Serbian', code: 'SR' }, checked: false },
    { id: 27, language: { label: 'Croatian', code: 'HR' }, checked: false },
    { id: 28, language: { label: 'Bosnian', code: 'BS' }, checked: false },
    { id: 29, language: { label: 'Albanian', code: 'SQ' }, checked: false },
    { id: 30, language: { label: 'Macedonian', code: 'MK' }, checked: false },
    { id: 31, language: { label: 'Slovenian', code: 'SL' }, checked: false },
    { id: 32, language: { label: 'Estonian', code: 'ET' }, checked: false },
    { id: 33, language: { label: 'Latvian', code: 'LV' }, checked: false },
    { id: 34, language: { label: 'Lithuanian', code: 'LT' }, checked: false },
    { id: 35, language: { label: 'Ukrainian', code: 'UK' }, checked: false },
    { id: 36, language: { label: 'Belarusian', code: 'BE' }, checked: false },
    { id: 37, language: { label: 'Georgian', code: 'KA' }, checked: false },
    { id: 38, language: { label: 'Armenian', code: 'HY' }, checked: false },
    { id: 39, language: { label: 'Azerbaijani', code: 'AZ' }, checked: false },
    { id: 40, language: { label: 'Kazakh', code: 'KK' }, checked: false },
    { id: 41, language: { label: 'Uzbek', code: 'UZ' }, checked: false },
    { id: 42, language: { label: 'Turkmen', code: 'TK' }, checked: false },
    { id: 43, language: { label: 'Kyrgyz', code: 'KY' }, checked: false },
    { id: 44, language: { label: 'Tajik', code: 'TG' }, checked: false },
    { id: 45, language: { label: 'Mongolian', code: 'MN' }, checked: false },
    { id: 46, language: { label: 'Vietnamese', code: 'VI' }, checked: false },
    { id: 47, language: { label: 'Thai', code: 'TH' }, checked: false },
    { id: 48, language: { label: 'Tagalog', code: 'TL' }, checked: false },
    { id: 49, language: { label: 'Indonesian', code: 'ID' }, checked: false },
    { id: 50, language: { label: 'Malay', code: 'MS' }, checked: false },
    { id: 51, language: { label: 'Burmese', code: 'MY' }, checked: false },
    { id: 52, language: { label: 'Khmer', code: 'KM' }, checked: false },
    { id: 53, language: { label: 'Lao', code: 'LO' }, checked: false },
    { id: 54, language: { label: 'Bengali', code: 'BN' }, checked: false },
    { id: 55, language: { label: 'Hindi', code: 'HI' }, checked: false },
    { id: 56, language: { label: 'Urdu', code: 'UR' }, checked: false },
    { id: 57, language: { label: 'Punjabi', code: 'PA' }, checked: false },
    { id: 58, language: { label: 'Tamil', code: 'TA' }, checked: false },
    { id: 59, language: { label: 'Telugu', code: 'TE' }, checked: false },
    { id: 60, language: { label: 'Marathi', code: 'MR' }, checked: false },
    { id: 61, language: { label: 'Gujarati', code: 'GU' }, checked: false },
    { id: 62, language: { label: 'Kannada', code: 'KN' }, checked: false },
    { id: 63, language: { label: 'Malayalam', code: 'ML' }, checked: false },
    { id: 64, language: { label: 'Sinhala', code: 'SI' }, checked: false },
    { id: 65, language: { label: 'Nepali', code: 'NE' }, checked: false },
    { id: 66, language: { label: 'Tibetan', code: 'BO' }, checked: false },
    { id: 67, language: { label: 'Bhutanese', code: 'DZ' }, checked: false },
    { id: 68, language: { label: 'Lingala', code: 'LN' }, checked: false },
    { id: 69, language: { label: 'Swahili', code: 'SW' }, checked: false },
    { id: 70, language: { label: 'Zulu', code: 'ZU' }, checked: false },
    { id: 71, language: { label: 'Xhosa', code: 'XH' }, checked: false },
    { id: 72, language: { label: 'Yoruba', code: 'YO' }, checked: false },
    { id: 73, language: { label: 'Hausa', code: 'HA' }, checked: false },
    { id: 74, language: { label: 'Igbo', code: 'IG' }, checked: false },
    { id: 75, language: { label: 'Amharic', code: 'AM' }, checked: false },
    { id: 76, language: { label: 'Somali', code: 'SO' }, checked: false },
    { id: 77, language: { label: 'Afar', code: 'AA' }, checked: false },
    { id: 78, language: { label: 'Tigrinya', code: 'TI' }, checked: false },
    { id: 79, language: { label: 'Oromo', code: 'OM' }, checked: false },
    { id: 80, language: { label: 'Ganda', code: 'LG' }, checked: false },
    { id: 81, language: { label: 'Kinyarwanda', code: 'RW' }, checked: false },
    { id: 82, language: { label: 'Kirundi', code: 'RN' }, checked: false },
    { id: 83, language: { label: 'Chichewa', code: 'NY' }, checked: false },
    { id: 84, language: { label: 'Sesotho', code: 'ST' }, checked: false },
    { id: 85, language: { label: 'Setswana', code: 'TN' }, checked: false },
    { id: 86, language: { label: 'Tswana', code: 'TS' }, checked: false },
    { id: 87, language: { label: 'Sotho', code: 'LS' }, checked: false },
    { id: 88, language: { label: 'Oshiwambo', code: 'KG' }, checked: false },
    { id: 89, language: { label: 'Herero', code: 'HZ' }, checked: false },
    { id: 90, language: { label: 'Ndonga', code: 'NG' }, checked: false },
    { id: 91, language: { label: 'Khoekhoe', code: 'QU' }, checked: false },
    { id: 92, language: { label: 'Damara', code: 'NA' }, checked: false },
    { id: 93, language: { label: 'Zarma', code: 'DZ' }, checked: false },
    { id: 94, language: { label: 'Wolof', code: 'WO' }, checked: false },
    { id: 95, language: { label: 'Twi', code: 'TW' }, checked: false },
    { id: 96, language: { label: 'Fulfulde', code: 'FF' }, checked: false },
    { id: 97, language: { label: 'Kanuri', code: 'KR' }, checked: false },
    { id: 98, language: { label: 'Mandingo', code: 'MN' }, checked: false },
    { id: 99, language: { label: 'Fulani', code: 'FF' }, checked: false },
    { id: 100, language: { label: 'Berber', code: 'BER' }, checked: false },
]

export const REGISTRATION_LANGUAGE = [
    { label: 'Russian', value: 'RU', isAvailable: true },
    { label: 'English', value: 'EN', isAvailable: true },
    { label: 'Spanish', value: 'ES', isAvailable: true },
    { label: 'French', value: 'FR', isAvailable: true },
    { label: 'German', value: 'DE', isAvailable: true },
    { label: 'Italian', value: 'IT', isAvailable: true },
    { label: 'Portuguese', value: 'PT', isAvailable: true },
    { label: 'Dutch', value: 'NL', isAvailable: true },
    { label: 'Swedish', value: 'SV', isAvailable: true },
    { label: 'Norwegian', value: 'NO', isAvailable: true },
    { label: 'Danish', value: 'DA', isAvailable: true },
    { label: 'Finnish', value: 'FI', isAvailable: true },
    { label: 'Japanese', value: 'JA', isAvailable: true },
    { label: 'Chinese', value: 'ZH', isAvailable: true },
    { label: 'Korean', value: 'KO', isAvailable: true },
    { label: 'Arabic', value: 'AR', isAvailable: true },
    { label: 'Hebrew', value: 'HE', isAvailable: true },
    { label: 'Turkish', value: 'TR', isAvailable: true },
    { label: 'Greek', value: 'EL', isAvailable: true },
    { label: 'Polish', value: 'PL', isAvailable: true },
    { label: 'Czech', value: 'CS', isAvailable: true },
    { label: 'Slovak', value: 'SK', isAvailable: true },
    { label: 'Hungarian', value: 'HU', isAvailable: true },
    { label: 'Romanian', value: 'RO', isAvailable: true },
    { label: 'Bulgarian', value: 'BG', isAvailable: true },
    { label: 'Serbian', value: 'SR', isAvailable: true },
    { label: 'Croatian', value: 'HR', isAvailable: true },
    { label: 'Bosnian', value: 'BS', isAvailable: true },
    { label: 'Albanian', value: 'SQ', isAvailable: true },
    { label: 'Macedonian', value: 'MK', isAvailable: true },
    { label: 'Slovenian', value: 'SL', isAvailable: true },
    { label: 'Estonian', value: 'ET', isAvailable: true },
    { label: 'Latvian', value: 'LV', isAvailable: true },
    { label: 'Lithuanian', value: 'LT', isAvailable: true },
    { label: 'Ukrainian', value: 'UK', isAvailable: true },
    { label: 'Belarusian', value: 'BE', isAvailable: true },
    { label: 'Georgian', value: 'KA', isAvailable: true },
    { label: 'Armenian', value: 'HY', isAvailable: true },
    { label: 'Azerbaijani', value: 'AZ', isAvailable: true },
    { label: 'Kazakh', value: 'KK', isAvailable: true },
    { label: 'Uzbek', value: 'UZ', isAvailable: true },
    { label: 'Turkmen', value: 'TK', isAvailable: true },
    { label: 'Kyrgyz', value: 'KY', isAvailable: true },
    { label: 'Tajik', value: 'TG', isAvailable: true },
    { label: 'Mongolian', value: 'MN', isAvailable: true },
    { label: 'Vietnamese', value: 'VI', isAvailable: true },
    { label: 'Thai', value: 'TH', isAvailable: true },
    { label: 'Tagalog', value: 'TL', isAvailable: true },
    { label: 'Indonesian', value: 'ID', isAvailable: true },
    { label: 'Malay', value: 'MS', isAvailable: true },
    { label: 'Burmese', value: 'MY', isAvailable: true },
    { label: 'Khmer', value: 'KM', isAvailable: true },
    { label: 'Lao', value: 'LO', isAvailable: true },
    { label: 'Bengali', value: 'BN', isAvailable: true },
    { label: 'Hindi', value: 'HI', isAvailable: true },
    { label: 'Urdu', value: 'UR', isAvailable: true },
    { label: 'Punjabi', value: 'PA', isAvailable: true },
    { label: 'Tamil', value: 'TA', isAvailable: true },
    { label: 'Telugu', value: 'TE', isAvailable: true },
    { label: 'Marathi', value: 'MR', isAvailable: true },
    { label: 'Gujarati', value: 'GU', isAvailable: true },
    { label: 'Kannada', value: 'KN', isAvailable: true },
    { label: 'Malayalam', value: 'ML', isAvailable: true },
    { label: 'Sinhala', value: 'SI', isAvailable: true },
    { label: 'Nepali', value: 'NE', isAvailable: true },
    { label: 'Tibetan', value: 'BO', isAvailable: true },
    { label: 'Bhutanese', value: 'DZ', isAvailable: true },
    { label: 'Lingala', value: 'LN', isAvailable: true },
    { label: 'Swahili', value: 'SW', isAvailable: true },
    { label: 'Zulu', value: 'ZU', isAvailable: true },
    { label: 'Xhosa', value: 'XH', isAvailable: true },
    { label: 'Yoruba', value: 'YO', isAvailable: true },
    { label: 'Hausa', value: 'HA', isAvailable: true },
    { label: 'Igbo', value: 'IG', isAvailable: true },
    { label: 'Amharic', value: 'AM', isAvailable: true },
    { label: 'Somali', value: 'SO', isAvailable: true },
    { label: 'Afar', value: 'AA', isAvailable: true },
    { label: 'Tigrinya', value: 'TI', isAvailable: true },
    { label: 'Oromo', value: 'OM', isAvailable: true },
    { label: 'Ganda', value: 'LG', isAvailable: true },
    { label: 'Kinyarwanda', value: 'RW', isAvailable: true },
    { label: 'Kirundi', value: 'RN', isAvailable: true },
    { label: 'Chichewa', value: 'NY', isAvailable: true },
    { label: 'Sesotho', value: 'ST', isAvailable: true },
    { label: 'Setswana', value: 'TN', isAvailable: true },
    { label: 'Tswana', value: 'TS', isAvailable: true },
    { label: 'Sotho', value: 'LS', isAvailable: true },
    { label: 'Oshiwambo', value: 'KG', isAvailable: true },
    { label: 'Herero', value: 'HZ', isAvailable: true },
    { label: 'Ndonga', value: 'NG', isAvailable: true },
    { label: 'Khoekhoe', value: 'QU', isAvailable: true },
    { label: 'Damara', value: 'NA', isAvailable: true },
    { label: 'Zarma', value: 'DZ', isAvailable: true },
    { label: 'Wolof', value: 'WO', isAvailable: true },
    { label: 'Twi', value: 'TW', isAvailable: true },
    { label: 'Fulfulde', value: 'F', isAvailable: true },
    { label: 'Kanuri', value: 'KR', isAvailable: true },
    { label: 'Mandingo', value: 'MN', isAvailable: true },
    { label: 'Fulani', value: 'FF', isAvailable: true },
    { label: 'Berber', value: 'BER', isAvailable: true }
]

export const FILTER_DAYS = [
    { id: 1, day: { label: 'Mon.', code: 'Mon' }, checked: false },
    { id: 2, day: { label: 'Tue.', code: 'Tue' }, checked: false },
    { id: 3, day: { label: 'Wed.', code: 'Wed' }, checked: false },
    { id: 4, day: { label: 'Thu.', code: 'Thu' }, checked: false },
    { id: 5, day: { label: 'Fri.', code: 'Fri' }, checked: false },
    { id: 6, day: { label: 'Sat.', code: 'Sat' }, checked: false },
    { id: 7, day: { label: 'Sun.', code: 'Sun' }, checked: false },
]
export const FILTER_HOURS = [
    { id: 1, time: { hours: '6-9', part: 'Morning' }, checked: false },
    { id: 2, time: { hours: '9-12', part: 'Late morning' }, checked: false },
    { id: 3, time: { hours: '12-15', part: 'Day' }, checked: false },
    {
        id: 4,
        time: { hours: '15-18', part: 'Second half of the day' },
        checked: false,
    },
    { id: 5, time: { hours: '18-21', part: 'Evening' }, checked: false },
    { id: 6, time: { hours: '21-24', part: 'Late evening' }, checked: false },
    { id: 7, time: { hours: '0-3', part: 'Night' }, checked: false },
    { id: 8, time: { hours: '3-6', part: 'After midnight' }, checked: false },
]

export const LANGUAGE_LEVEL = [
    { value: 'Beginner', label: 'A1' },
    { value: 'Elementary', label: 'A2' },
    { value: 'Intermediate', label: 'B1' },
    { value: 'Upper-Intermediate', label: 'B2' },
    { value: 'Advanced', label: 'C1' },
    { value: 'Expert', label: 'C2' },
    { value: 'Native', label: 'Native' },
]